# Generated by Django 5.1.2 on 2024-11-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='related_data',
            new_name='released_date',
        ),
    ]
