# Generated by Django 5.1.2 on 2024-11-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_email_address_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_address',
        ),
    ]
